name: screenstakeios
options:
  bundleIdPrefix: com.screenstakeios
  deploymentTarget:
    iOS: 17.4
  createIntermediateGroups: true

targets:
  screenstakeios:
    type: application
    platform: iOS
    sources: 
      - path: screenstakeios
        excludes:
          - "**/.DS_Store"
          - "Preview Content"
        createIntermediateGroups: true
        type: group
        children:
          - screenstakeiosApp.swift
          - AppCoordinator.swift
          - path: Models
            createIntermediateGroups: true
            children:
              - DataModels.swift
              - PersistenceManager.swift
              - AuthModels.swift
              - AuthManager.swift
          - path: Views
            createIntermediateGroups: true
            children:
              - ContentView.swift
              - RootContainerView.swift
              - LandingView.swift
              - AppSelectionView.swift
              - StakeSetupView.swift
              - PaymentSetupView.swift
              - AuthView.swift
              - EmailVerificationView.swift
              - PaymentMethodSetupView.swift
    resources:
      - screenstakeios/Assets.xcassets
      - screenstakeios/Preview Content
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.screenstakeios.screenstakeios
        PRODUCT_NAME: screenstakeios
        SWIFT_VERSION: 5.0
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        DEVELOPMENT_ASSET_PATHS: "\"screenstakeios/Preview Content\""
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        IPHONEOS_DEPLOYMENT_TARGET: 17.4
      debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        DEBUG_INFORMATION_FORMAT: dwarf
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      release:
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        SWIFT_OPTIMIZATION_LEVEL: "-O"