name: screenstakeios

options:
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    exactVersion: 10.27.0
  Stripe:
    url: https://github.com/stripe/stripe-ios
    exactVersion: 23.27.0

targets:
  screenstakeios:
    type: application
    platform: iOS
    sources:
      - path: screenstakeios
        excludes:
          - "**/.DS_Store"
          - "Preview Content"
        createIntermediateGroups: true
        type: group
        children:
          - screenstakeiosApp.swift
          - AppCoordinator.swift
          - ColorExtensions.swift  # ← ADD THIS LINE
          - path: Models
            createIntermediateGroups: true
            children:
              - DataModels.swift
              - PersistenceManager.swift
              - AuthModels.swift
              - AuthManager.swift
              - FirebaseAuthManager.swift
              - StripePaymentManager.swift
              - StakeMonitoringService.swift
          - path: Views
            createIntermediateGroups: true
            children:
              - ContentView.swift
              - RootContainerView.swift
              - LandingView.swift
              - AppSelectionView.swift
              - StakeSetupView.swift
              - PaymentSetupView.swift
              - ApplePaySetupView.swift
              - AuthView.swift
              - EmailVerificationView.swift
              - PaymentMethodSetupView.swift
              - FirebaseEmailVerificationView.swift
              - SMSVerificationView.swift
    resources:
      - screenstakeios/Assets.xcassets
      - screenstakeios/Preview Content
      - screenstakeios/GoogleService-Info.plist
    dependencies:
      # --- Firebase ---
      - package: Firebase
        product: FirebaseAuth
      # --- Stripe ---
      - package: Stripe
        product: StripePaymentSheet
      - package: Stripe
        product: StripeApplePay
      # --- Apple SDKs ---
      - sdk: PassKit.framework
      - sdk: StoreKit.framework
    settings:
      base:
        # Signing
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: KAZMRW253H
        PRODUCT_BUNDLE_IDENTIFIER: com.andyg.screenstake

        # App meta
        PRODUCT_NAME: screenstakeios
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1

        # Swift / build
        SWIFT_VERSION: 5.10
        GENERATE_INFOPLIST_FILE: YES
        IPHONEOS_DEPLOYMENT_TARGET: 16.0

        # Info.plist keys
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

        # Assets / previews
        DEVELOPMENT_ASSET_PATHS: "\"screenstakeios/Preview Content\""
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

        # Permissions text
        INFOPLIST_KEY_NSFaceIDUsageDescription: "Authenticate payments securely with Face ID"
        INFOPLIST_KEY_NSCameraUsageDescription: "Scan payment cards for easier entry"
        INFOPLIST_KEY_NSUserTrackingUsageDescription: "Track your screen time to help you meet your goals"

        # Background modes
        INFOPLIST_KEY_UIBackgroundModes:
          - fetch
          - processing
          - remote-notification

        # URL schemes (Stripe redirect)
        INFOPLIST_KEY_CFBundleURLTypes: '[{"CFBundleURLSchemes":["screenstake"],"CFBundleURLName":"com.screenstakeios"}]'

      debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        DEBUG_INFORMATION_FORMAT: dwarf
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"

      release:
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        SWIFT_OPTIMIZATION_LEVEL: "-O"

schemes:
  screenstakeios:
    shared: true
    build:
      targets:
        screenstakeios: all
    run:
      config: Debug